export const COUNTRIES = [
  "Indonesia",
  "Singapore",
  "Malaysia",
  "Australia",
  "United States",
  "United Kingdom",
  "Germany",
  "France",
  "Netherlands",
  "Japan",
  "South Korea",
  "China",
  "India",
  "United Arab Emirates",
  "Canada",
  "New Zealand",
  "Italy",
  "Spain",
  "Switzerland",
  "Sweden",
  "Russia",
  "Brazil",
  "South Africa",
  "Philippines",
  "Thailand",
  "Vietnam",
  "Other",
];
