"use client";
import {
  Sun,
  Moon,
  Menu,
  Waves,
  ChefHat,
  Shirt,
  Footprints,
  Tv,
  Wifi,
  FireExtinguisher,
  ShieldPlus,
  Wind,
  Users,
  BedDouble,
  Bath,
  Maximize,
  Flame,
  Wine,
  Coffee,
  Laptop,
  ParkingCircle,
  Sparkles,
  PersonStanding,
  Plane,
  UtensilsCrossed,
  Baby,
  Lock,
  Trees,
  Star,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  Home,
  BadgeCheck,
  HandCoins,
  ConciergeBell,
  Check,
  X,
  User,
  Calendar,
  Gift,
  Luggage,
  Image as ImageIcon,
  Plus,
} from "lucide-react";

import {
  FaInstagram,
  FaFacebookF,
  FaWhatsapp,
  FaXTwitter,
} from "react-icons/fa6";

const ICON_MAP = {
  sun: Sun,
  moon: Moon,
  menu: Menu,
  pool: Waves,
  jacuzzi: Waves,
  kitchen: ChefHat,
  wardrobe: Shirt,
  slippers: Footprints,
  tv: Tv,
  wifi: Wifi,
  extinguisher: FireExtinguisher,
  firstaid: ShieldPlus,
  safetybox: Lock,
  ac: Wind,
  hairdryer: Wind,
  garden: Trees,
  bbq: Flame,
  minibar: Wine,
  breakfast: Coffee,
  coffee: Coffee,
  bath: Bath,
  workspace: Laptop,
  chef: ChefHat,
  parking: ParkingCircle,
  spa: Sparkles,
  massage: Sparkles,
  yoga: PersonStanding,
  cleaning: Sparkles,
  airport: Plane,
  dining: UtensilsCrossed,
  babycot: Baby,
  highchair: Baby,
  guests: Users,
  beds: BedDouble,
  baths: Bath,
  size: Maximize,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronDown: ChevronDown,
  instagram: FaInstagram,
  facebook: FaFacebookF,
  whatsapp: FaWhatsapp,
  xTwitter: FaXTwitter,
  close: X,
  home: Home,
  verified: BadgeCheck,
  price: HandCoins,
  concierge: ConciergeBell,
  success: Check,
  check: Check,
  lock: Lock,
  star: Star,
  user: User,
  users: Users,
  calendar: Calendar,
  gift: Gift,
  briefcase: Luggage,
  image: ImageIcon,
  plus: Plus,
  default: Star,
};

export function Icon({
  name,
  size = 18,
  strokeWidth = 1.6,
  className = "",
  style,
}) {
  const LucideIcon = ICON_MAP[name] || ICON_MAP.default;
  return (
    <LucideIcon
      size={size}
      strokeWidth={strokeWidth}
      className={className}
      style={style}
    />
  );
}
